link/link/link/models.py
from common.extensions import db
from common.utils import timestamp


link_tag_table = db.Table(
    'link_tag',
    db.Column('link_id', db.Integer, db.ForeignKey('link.id'), nullable=False),
    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'), nullable=False)
)


class Link(db.Model):
    """
    Link model
    Fields: id <int>,
            created_at <int>,
            updated_at <int>,
            name <str>,
            url <str>,
            active <bool>,
            website_image <str>,
            description <str>,
            user_id <int>,
            tags <Tag>
    Input fields: name, url, description
    """
    __tablename__ = 'link'
    __searchable__ = ['name', 'url', 'description']

    id = db.Column(db.Integer, primary_key=True)

    created_at = db.Column(db.Integer, default=timestamp)
    updated_at = db.Column(db.Integer, default=timestamp)

    name = db.Column(db.String(256), nullable=False, unique=True)
    url = db.Column(db.Text, nullable=False)
    active = db.Column(db.Boolean, default=True)
    website_image = db.Column(db.String(256))
    description = db.Column(db.Text, nullable=False)

    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    tags = db.relationship('Tag',
                           secondary=link_tag_table,
                           backref=db.backref('links', lazy='dynamic'))

    def to_json(self):
        """
        Convert link object to dict (json like)
        :return: dict
        """
        return {
            'ID': self.id,
            'created_at': self.created_at,
            'updated_at': self.updated_at,
            'url': self.url,
            'active': self.active,
            'name': self.name,
            'image': self.website_image,
            'description': self.description,
            'tags': [tag.to_json() for tag in self.tags]
        }

    def __repr__(self):
        """
        Represent link object
        :return: str
        """
        return '<LINK ID={id} URL={url} ACTIVE={active}>'.format(
            id=self.id, url=self.url, active=self.active)

    @classmethod
    def create(cls, name, url, description):
        """
        Create link object and store in database
        :param cls Link: Class inctanse
        :param name str: website name
        :param url str: website url
        :param description str: describe website
        :return: Link object
        """
        link = cls(name=name, url=url, description=description)
        db.session.add(link)
        db.session.commit()
        return link


class Tag(db.Model):
    """
    Tag model
    Fields: id <int>,
            created_at <int>,
            updated_at <int>,
            name <str>
    Input fields: name <str>
    """
    __tablename__ = 'tag'
    __searchable__ = ['name']

    id = db.Column(db.Integer, primary_key=True)

    created_at = db.Column(db.Integer, default=timestamp)
    updated_at = db.Column(db.Integer, default=timestamp)

    name = db.Column(db.String(50), nullable=False)

    @classmethod
    def create(cls, name):
        """
        Create Tag object and store in database
        :param cls Tag: Class inctanse
        :param name str: Name of tag
        :return: Tag object
        """
        tag = cls(name=name)
        db.session.add(tag)
        db.session.commit()
        return tag

    def to_json(self):
        """
        Convert tag object to dict (json like)
        :return: dict
        """
        return {
            'ID': self.id,
            'name': self.name,
            'created_at': self.created_at,
            'updated_at': self.updated_at
        }

    def __repr__(self):
        """
        Represent tag object
        :return: str
        """
        return '<TAG ID={id} NAME={name}>'.format(
            id=self.id, name=self.name)

link/link/link/__init__.py
from flask import Blueprint


bp_link = Blueprint('bp_link', __name__)

from . import views

link/link/link/views.py
from flask import render_template, request, flash, redirect, url_for
from urllib.parse import urlparse
from flask_login import current_user, login_required

from link import bp_link
from link import utils as fetch
from common.extensions import db
from link.models import Link, Tag


@bp_link.route('/', methods=['GET'])
def index():
    per_page = 10
    page = request.args.get('page', 1, type=int)
    links = Link.query.order_by(
        Link.created_at.desc()
    ).paginate(page, per_page=per_page, error_out=False)
    return render_template('link/index.html', links=links)


@bp_link.route('/create', methods=['GET'])
@login_required
def create():
    return render_template('link/create.html')


@bp_link.route('/store', methods=['POST'])
@login_required
def store():
    data = request.form.copy()
    # TODO better validation
    if data and 'url' in data.keys() and 'description' in data.keys() and \
            'tags' in data.keys() and data['tags']:
        link = Link.query.filter_by(url=data['url']).first()
        if not link:
            url_info = urlparse(data['url'])
            link = Link(
                user_id=current_user.id,
                url=data['url'],
                description=data['description'],
                name=data['name'])
            for tag_name in data['tags'].split(','):
                old_tag = Tag.query.filter_by(name=tag_name).first()
                if old_tag:
                    link.tags.append(old_tag)
                    db.session.add(link)
                    continue
                tag = Tag(name=tag_name)
                db.session.add(tag)
                link.tags.append(tag)
            db.session.add(link)
            db.session.commit()
            fetch.make_img(data['url'], str(link.id))
            return redirect(url_for('bp_link.show', id=link.id))
        flash("Data exist", "error")
        return redirect(url_for('bp_link.show', id=link.id))
    flash("fill require inputs", "error")
    return redirect(url_for('bp_link.create'))


@bp_link.route('/p2i_callback', methods=['GET', 'POST'])
def call_back():
    if 'status' in request.form and request.form['status'] == 'finished':
        link_id = request.args.get('link_id', '')
        if not link_id:
            return '', 200
        link = Link.query.filter_by(id=link_id).first()
        link.website_image = fetch.write_img(request.form['image_url'])
        db.session.add(link)
        db.session.commit()
    return '', 200


@bp_link.route('/<int:id>', methods=['GET'])
def show(id):
    link = Link.query.filter_by(id=id).first()
    if not link:
        flash("Link does not exist", "error")
        return redirect('bp_link.index')
    return render_template('/link/show.html', link=link)

link/link/templates/link/create.html
{% extends "layouts/layout.default.html" %}

{% block title %}Create-Link{% endblock %}

{% block section %}
<section class"section">
    <div class="container">
        <h2 class="title">Add link</h2>
        <form id="link-create" method="POST" action="{{ url_for('bp_link.store') }}">
            <div class="field">
                <label class="label">Name</label>
                <div class="control">
                    <input name="name" class="input is-rounded" type="text" placeholder="Website name" required>
                </div>
            </div>

            <div class="field">
                <label class="label">URL</label>
                <div class="control">
                    <input name="url" class="input is-rounded" type="text" placeholder="www.duckduckgo.com" required>
                </div>
            </div>

            <div class="field">
                <label class="label">Tags</label>
                <div class="control">
                    <input name="tags" class="input is-rounded" type="text" placeholder="search engine, weather, test" required>
                </div>
            </div>

            <!-- <div class="field"> -->
                <!-- <label class="label">Website image</label> -->
                <!-- <div class="control is-grouped"> -->
                    <!-- <button class="button is-link" id="make-web-img-create">Get website image</button> -->
                    <!-- <input id="img-create" name="web_img"  class="input is-rounded" type="text" placeholder="www.duckduckgo.com" disabled> -->
                <!-- </div> -->
            <!-- </div> -->

            <div class="field">
                <label class="checkbox has-text-black">
                    <input name="active" type="checkbox">
                    Is url active or not
                </label>
            </div>

            <div class="field">
                <label class="label">Description</label>
                <div class="control">
                    <textarea name="description" class="textarea is-rounded" type="text" placeholder="Success textarea"></textarea>
                </div>
            </div>

            <div class="field is-grouped">
                <div class="control">
                    <input class="button is-link" type="submit" value="Submit">
                </div>
            </div>
        </form>
        <br><br><br>
    </div>
</section>
{% endblock %}

{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/sugar/1.4.1/sugar.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script src="{{ url_for('static', filename='js/jquerymy.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/webimg.js') }}"></script>
{% endblock %}

link/link/templates/link/index.html
{% extends "layouts/layout.default.html" %}

{% block title %}Link Project{% endblock %}

{% block section %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
<section class="section">
    <div class="container">
    <h1 class="title">
        Links
    </h1>
    {% if links %}
        <p class="subtitle">
            {% for link in links.items %}
                <article class="media">
                  <figure class="media-left">
                    <p class="image is-64x64">
                        <img src="{{ link.website_image }}">
                    </p>
                  </figure>
                  <div class="media-content">
                    <div class="content">
                      <p class="has-text-black">
                          <strong>{{ link.name }}</strong> <small>{{ Moment(link.created_at).calendar() }}</small>
                        <br>
                        {{ link.description }}
                      </p>
                    </div>
                    <nav class="level is-mobile">
                      <div class="level-left">
                        <!-- <a class="level-item"> -->
                          <!-- <span class="icon is-small"><i class="fas fa-reply"></i></span> -->
                        <!-- </a> -->
                        <!-- <a class="level-item"> -->
                          <!-- <span class="icon is-small"><i class="fas fa-retweet"></i></span> -->
                        <!-- </a> -->
                        <a class="level-item" href="{{ url_for('bp_link.show', id=link.id) }}">
                          <span class="icon is-medium"><i class="fas fa-arrow-circle-right "></i></span>
                        </a>
                        <!-- <a class="level-item"> -->
                          <!-- <span class="icon is-small"><i class="fas fa-heart"></i></span> -->
                        <!-- </a> -->
                      </div>
                      <div class="level-right tags">
                          {% for tag in link.tags %}
                          <!-- TODO make get link by tag route -->
                            <a class="level-item has-text-white" href="#">
                                <span class="tag is-small is-rounded is-link">{{ tag.name }}</span>
                            </a>
                          {% endfor %}
                      </div>
                    </nav>
                  </div>
                  <!-- <div class="media-right"> -->
                    <!-- <button class="delete"></button> -->
                  <!-- </div> -->
                </article>
            {% endfor %}
        </p>
    {% else %}
        <p class="subtitle">There is no link yet!</p>
    {% endif%}
    </div>
</section>
{% endblock %}

link/link/templates/link/show.html
{% extends "layouts/layout.default.html" %}

{% block title %}Show-Link{% endblock %}

{% block section %}
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column is-4">
                <img src="{{ link.website_image }}" alt="{{ link.name }}">
            </div>
        </div>
    </div>
</section>
{% endblock %}

link/link/templates/link/update.html
{% extends "layouts/layout.default.html" %}

{% block title %}Update-Link{% endblock %}

{% block section %}
<section class"section">
    <div class="container">
        <h2 class="title">Update link</h2>
        <form method="POST" action="{{ url_for('bp_link.store') }}">
            <div class="field">
                <label class="label">Name</label>
                <div class="control">
                    <input name="name" class="input is-success" type="text" value="{{ link.name }}" placeholder="duckduckgo" required>
                </div>
            </div>

            <div class="field">
                <label class="label">URL</label>
                <div class="control">
                    <input name="url" class="input is-success" type="text" value="{{  link.url }}" placeholder="www.duckduckgo.com" required>
                </div>
            </div>

            <div class="field">
                <label class="label">Website image</label>
                <div class="control">
                    <input name="web_img"  class="input is-success" type="text" value="{{ link.img }}" placeholder="link/img/duckduckgo.com/duckduckgo.com.jpg.jpg">
                </div>
            </div>

            <label class="checkbox">
                <input name="active" type="checkbox">
                Is url active or not
            </label>

            <div class="field">
                <label class="label">Description</label>
                <div class="control">
                    <textarea name="description" class="textarea is-success" type="text" value="{{ link.description }}" placeholder="Success textarea" required></textarea>
                </div>
            </div>

            <div class="select is-multiple">
                <select multiple size="3">
                    {% for tag in link.tags %}
                    <option value="Argentina">Argentina</option>
                    {% endfor %}
                </select>
            </div>

            <div class="field is-grouped">
                <div class="control">
                    <input type="submit" class="button is-link" value="Submit">
                </div>
            </div>
        </form>
    </div>
</section>
{% endblock %}